title: MGCI Robotics
description: Welcome to the website Marc Garneau CI's Robotics club! The club aims to educate students and give them exposure to robotics. It provides hands-on and interactive experiences with robotics while competing in tournaments to promote teamwork. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
